language: node_js

node_js:
  - 8.1.3

install:
  - npm i yarn -g
  - yarn install

script:
  - yarn test
  - yarn run webpack

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
